apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-add-task-svc
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-add-task
  ports:
  - port: {{ .Values.add_task.serviceport }}
    targetPort: {{ .Values.add_task.port }}
