apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-todo-ui-ingress
  namespace: app
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
  - http:
      paths:
      - pathType: prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-todo-ui-svc
            port: 
              number: {{ .Values.microui.serviceport }}
