common:
  acr_server_name: acrtodoappdev01.azurecr.io
  ingressClassName: nginx
  connection_string: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:mssqldbserverdev.database.windows.net,1433;Database=sqldbdev;Uid=sqladminuser;Pwd=Test@12345;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

microui:
  image: microtodoui
  uitag: 36
  replicas: 1
  port: 80
  serviceport: 80


get_task:
  image: microtodogettask
  gettag: 26
  replicas: 1
  port: 8000
  serviceport: 80


delete_task:
  image: microtododeletetask
  deletetag: 23
  replicas: 1
  port: 8000
  serviceport: 80


add_task:
  image: microtodoaddtask
  addtag: 30
  replicas: 1
  port: 8000
  serviceport: 80
