# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{.Release.Name}}-get-task-ingress
#   namespace: app
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   ingressClassName: {{ .Values.common.ingressClassName }}
#   rules:
#   - http:
#       paths:
#       - pathType: ImplementationSpecific
#         path: "/get-task(/|$)(.*)"
#         backend:
#           service:
#             name: {{ .Release.Name }}-get-task-svc
#             port:
#               number: {{ .Values.get_task.serviceport }}


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-get-task-ingress
  namespace: app
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /get-task
        backend:
          service:
            name: {{ .Release.Name }}-get-task-svc
            port:
              number: {{ .Values.get_task.serviceport }}
