apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-todo-ui
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-todo-ui
  ports:
  - port: {{ .Values.get_task.serviceport }}
    targetPort: {{ .Values.get_task.port }}
