name: ArgoCD setup

on: workflow_dispatch

jobs:
  setup-adgocd:
    runs-on: raja:rana

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
        
      - name: PowerShell script to install argocd
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: 
            kubectl create namespace argocd
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: PowerShell script to create project
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: 
            kubectl apply -f argocd-project.yaml

      - name: PowerShell script to create application
        uses: Amadevus/pwsh-script@v2.0.3
        with:
          script: 
            kubectl apply -f argocd-app.yaml
                 
